apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-go-ptxumehk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-go-ptxumehk 
  name: github-tests-go-ptxumehk
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-tests-go-ptxumehk 
